# Copyright (c) 2021, 2022 Oracle and/or its affiliates.
# Licensed under the Universal Permissive License v1.0 as shown at https://oss.oracle.com/licenses/upl.
---
name: Login to Oracle Cloud Infrastructure Registry (OCIR)
description: Log Docker and Podman into your Oracle Cloud Infrastructure Registry instance
inputs:
  auth_token:
    description: Auth token for the OCI user to login with
    required: true
outputs:
  ocir_endpoint:
    description: The OCIR endpoint to which the user has been authenticated
  ocir_username:
    description: The full username required by OCIR for login purposes
branding:
  icon: 'circle'
  color: 'red'
runs:
  using: 'node12'
  main: 'dist/index.js'
  post: 'dist/index.js'
